### ISSUE TITLE
Timed lyrics is broken

### ISSUE THREAD

**Issue by WeeeeeeeeeeS** [DuncteBot/java-timed-lyrics#10]
is it just me or what

**Comment by duncte123** [comment]
Please add some actual info instead of just saying "does not work"

**Comment by WeeeeeeeeeeS** [comment]
A lot of tracks that used to work and load timed lyrics now return nothing. (Some return the entire lyrics but not timed lines)

**Comment by WeeeeeeeeeeS** [comment]
Im not sure if this plugin works the same way as [this one](https://github.com/DRSchlaubi/lyrics.kt/commit/21b293c330ff5254154fdfae88772ad4b19fded2), but something seems to be wrong.

**Comment by duncte123** [comment]
Plugin is not broken, youtube is just sending text lyrics
